import { Container } from '@mantine/core';
import axios from 'axios';
import { format } from 'date-fns';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { MatchI } from '../@types/Match';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [matches, setMatches] = useState([]);

  useEffect(() => {
    axios.get('http://localhost:4000/matches').then((res) => {
      const matches = res.data;
      const sortedMatches = matches.map((match: MatchI) => {
        return {
          ...match,
          matches_participants: {
            ...match.matches_participants.sort(
              (a, b) => a.placement.valueOf() - b.placement.valueOf()
            ),
            matches_participants_units:
              match.matches_participants.map((participant) => {
                return {
                  ...participant,
                  matches_participants_units_units:
                    participant.matches_participants_units.sort(
                      (a, b) => b.tier.valueOf() - a.tier.valueOf()
                    ),
                };
              }),
          },
        };
      });
      setMatches(sortedMatches);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          content="Generated by create next app"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Container>
        {matches &&
          matches.map((match: MatchI) => {
            return (
              <div
                className={styles.match}
                key={format(match.game_datetime, 'dd/MM/yyyy HH:mm')}
              >
                <span>
                  Game played at{' '}
                  {format(match.game_datetime, 'dd/MM/yyyy HH:mm')} on{' '}
                  {match.region}
                </span>
              </div>
            );
          })}
      </Container>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
